### ISSUE TITLE
Slowing down

### ISSUE THREAD

**Issue by tombarys** [dive2Pro/roam-aliases#1]
Hi, after installing the plugin, my graph became unusably slow. I unistalled it immediatelly.

**Comment by dive2Pro** [comment]
Fair enough.I didn't testing on large graph.  
fix code is under review

**Comment by tombarys** [comment]
Thank you very much. In fact, working aliases are probably the last thing that users are missing in Roam :)

**Comment by dive2Pro** [comment]
Performance issues should be fixed, please update
